add:
  -
    - 1
    - 1
    - 2
  -
    - 90
    - 10
    - 100
  -
    - 10.0
    - 2
    - 12.0
  -
    - 0.1
    - 2.1
    - 2.2
sub:
  -
    - 2
    - 3
    - -1
  -
    - 0.9
    - 0.2
    - 0.7
  -
    - 500
    - 300
    - 200
  -
    - 10
    - 12.5
    - -2.5
mul:
  -
    - 2
    - 3
    - 6
  -
    - 1
    - 0.2
    - 0.2
  -
    - -1
    - 3
    - -3
  -
    - -10
    - 0
    - 0
div:
  -
    - 8
    - 2
    - 4
  -
    - 5
    - 0
    - 7
  -
    - 0.9
    - 3
    - 0.3
  -
    - -0.4
    - 2
    - -0.2
